### ISSUE TITLE
Pack the two plugins into a Module Suite?

### ISSUE THREAD

**Issue by jonathanlermitage** [markiewb/nb-paste-to-new-file#1]
Hi,
could you pack the two plugins into a single Module Suite?
Or pack the two nbm files into a single ZIP file before asking for validation.
Thx.

**Comment by markiewb** [comment]
@jonathanlermitage: 
Does the plugin center supports signed module suites for validation?

The reason for splitting the plugin into two parts is that the core-plugin should have no dependencies to the java modules and thus it can be used even in the PHP/HTML5/C++-distributions of NetBeans.

**Comment by jonathanlermitage** [comment]
Yes, actually you won't sign the Module Suite but every single module.

Meanwhile, I think you can ignore the present issue: I had not realized why your plugin was divided into two parts :-)
Sorry for the confusion and thank you for all your nice plugins! (I use many of them)

**Comment by markiewb** [comment]
@jonathanlermitage: No problem. You are welcome!
